window.matchReplays = [
    {
        "date": "28/02/2025",
        "teamA": ["Constantin", "Enos", "Abdel Karim", "Abdel Rafik", "Anasse"],
        "scoreA": 13,
        "teamB": ["Luka", "Mahamat", "Dorian", "Jesus", "Nabil"],
        "scoreB": 8,
        "link": "https://drive.google.com/drive/folders/14kRwWrWo5QRMlbRC2jRseEDPMnWWzSSU?usp=drive_link",
        "timeline": [
            { "min": "4", "scorer": "Jesus", "score": "0-1" },
            { "min": "6", "scorer": "Enos", "score": "1-1" },
            { "min": "11", "scorer": "Abdel Karim", "score": "2-1" },
            { "min": "12", "scorer": "Anasse", "score": "3-1" },
            { "min": "13", "scorer": "Abdel Karim", "score": "4-1" },
            { "min": "15", "scorer": "Enos", "score": "5-1" },
            { "min": "17", "scorer": "Dorian", "score": "5-1" },
            { "min": "20", "scorer": "Abdel Rafik", "score": "6-2" },
            { "min": "23", "scorer": "Constantin", "score": "7-2" },
            { "min": "23", "scorer": "Constantin", "score": "8-2" },
            { "min": "24", "scorer": "Nabil", "score": "8-3" },
            { "min": "26", "scorer": "Abdel Karim", "score": "9-3" },
            { "min": "27", "scorer": "Luka", "score": "9-4" },
            { "min": "28", "scorer": "Mahamat", "score": "9-5" },
            { "min": "29", "scorer": "Enos", "score": "10-5" },
            { "min": "35", "scorer": "Mahamat", "score": "10-6" },
            { "min": "36", "scorer": "Anasse", "score": "11-6" },
            { "min": "37", "scorer": "Nabil", "score": "11-7" },
            { "min": "39", "scorer": "Nabil", "score": "11-8" },
            { "min": "40", "scorer": "Abdel Karim", "score": "12-8" },
            { "min": "41", "scorer": "Enos", "score": "13-8" }
        ]
    },
    {
        "date": "06/05/2025",
        "teamA": ["Constantin", "Enos", "François", "Stephane", "Seyed"],
        "scoreA": 12,
        "teamB": ["Abdel Karim", "Jesus", "Adrien", "Andreja", "Driss"],
        "scoreB": 11,
        "link": "https://drive.google.com/drive/folders/1i8fM-tSV3szppXl4_eNR1zaSaQuj08NK?usp=drive_link",
        "timeline": [
            { "min": "1", "scorer": "Stef", "score": "1-0" },
            { "min": "6", "scorer": "Inconnu", "score": "1-1" },
            { "min": "6", "scorer": "Constantin", "score": "2-1" },
            { "min": "11", "scorer": "Constantin", "score": "3-1" },
            { "min": "18", "scorer": "Inconnu", "score": "3-2" },
            { "min": "24", "scorer": "Inconnu", "score": "3-3" },
            { "min": "29", "scorer": "Constantin", "score": "4-3" },
            { "min": "29", "scorer": "C", "score": "5-3" },
            { "min": "32", "scorer": "Constantin", "score": "6-3" },
            { "min": "33", "scorer": "Inconnu", "score": "6-4" },
            { "min": "35", "scorer": "Inconnu", "score": "6-5" },
            { "min": "37", "scorer": "C", "score": "7-5" },
            { "min": "38", "scorer": "Driss", "score": "7-6" },
            { "min": "42", "scorer": "Inconnu", "score": "7-7" },
            { "min": "43", "scorer": "Driss", "score": "7-8" },
            { "min": "46", "scorer": "Enos", "score": "8-8" },
            { "min": "46", "scorer": "Enos", "score": "9-8" },
            { "min": "47", "scorer": "Inconnu", "score": "10-8" },
            { "min": "49", "scorer": "Inconnu", "score": "11-8" },
            { "min": "52", "scorer": "Inconnu", "score": "11-9" },
            { "min": "53", "scorer": "Inconnu", "score": "11-10" },
            { "min": "55", "scorer": "Inconnu", "score": "12-10" },
            { "min": "55", "scorer": "Driss", "score": "12-11" }
        ]
    },
    {
        "date": "14/05/2025",
        "teamA": ["Anasse", "Seyed", "Driss", "François", "Ahmed"],
        "scoreA": 7,
        "teamB": ["Jesus", "Sofiane", "Constantin", "Loïc", "Florent"],
        "scoreB": 10,
        "link": "https://drive.google.com/drive/folders/1rDpFIp2HEdq7YgAEOu69_W19ZtWwZ-Xz?usp=drive_link",
        "timeline": [
            { "min": "2", "scorer": "Inconnu", "score": "0-1" },
            { "min": "3", "scorer": "Inconnu", "score": "1-1" },
            { "min": "9", "scorer": "Inconnu", "score": "2-1" },
            { "min": "11", "scorer": "Inconnu", "score": "2-2" },
            { "min": "12", "scorer": "C", "score": "3-2" },
            { "min": "22", "scorer": "C", "score": "4-2" },
            { "min": "26", "scorer": "Inconnu", "score": "5-2" },
            { "min": "28", "scorer": "Inconnu", "score": "5-3" },
            { "min": "29", "scorer": "Inconnu", "score": "5-4" },
            { "min": "33", "scorer": "Inconnu", "score": "6-4" },
            { "min": "35", "scorer": "Inconnu", "score": "6-5" },
            { "min": "42", "scorer": "Inconnu", "score": "6-6" },
            { "min": "48", "scorer": "Inconnu", "score": "6-7" },
            { "min": "52", "scorer": "Inconnu", "score": "6-8" },
            { "min": "55", "scorer": "Inconnu", "score": "6-9" },
            { "min": "57", "scorer": "Inconnu", "score": "6-10" },
            { "min": "58", "scorer": "Inconnu", "score": "7-10" }
        ]
    },
    {
        "date": "16/05/2025",
        "teamA": ["Seyed", "Anasse", "Ahmed", "François", "Driss"],
        "scoreA": 9,
        "teamB": ["Romain", "Constantin", "Wasim", "Lamine", "Florent"],
        "scoreB": 8,
        "link": "https://drive.google.com/drive/folders/1N403K58P4H76cKRYXuIRgwlKSyV_rptk?usp=drive_link",
        "timeline": [
            { "min": "5", "scorer": "Francois", "score": "0-1" },
            { "min": "5", "scorer": "Romain", "score": "1-1" },
            { "min": "6", "scorer": "Romain", "score": "2-1" },
            { "min": "13", "scorer": "Flo", "score": "3-1" },
            { "min": "19", "scorer": "Ahmed", "score": "3-2" },
            { "min": "20", "scorer": "Driss", "score": "3-3" },
            { "min": "22", "scorer": "Wasim", "score": "4-3" },
            { "min": "25", "scorer": "Wasim", "score": "5-3" },
            { "min": "28", "scorer": "Constantin", "score": "6-3" },
            { "min": "30", "scorer": "Flo", "score": "7-3" },
            { "min": "35", "scorer": "Lamine", "score": "8-3" },
            { "min": "43", "scorer": "Francois", "score": "8-4" },
            { "min": "44", "scorer": "Francois", "score": "8-5" },
            { "min": "45", "scorer": "Driss", "score": "8-6" },
            { "min": "49", "scorer": "Anasse", "score": "8-7" },
            { "min": "53", "scorer": "Seyed", "score": "8-8" },
            { "min": "55", "scorer": "Francois", "score": "8-9" }
        ]
    },
    {
        "date": "20/05/2025",
        "teamA": ["Seyed", "Enos", "Anasse", "Adrien", "Florent"],
        "scoreA": 11,
        "teamB": ["Abdel Karim", "Constantin", "Mahamat", "Tsio", "Romain"],
        "scoreB": 15,
        "link": "https://drive.google.com/drive/folders/1sBb7SR-ZEbpd_zTJDmDIJa1agQ_n21Qk?usp=drive_link",
        "timeline": [
            { "min": "2", "scorer": "Inconnu", "score": "0-1" },
            { "min": "6", "scorer": "Constantin", "score": "0-2" },
            { "min": "8", "scorer": "Inconnu", "score": "0-3" },
            { "min": "10", "scorer": "Constantin", "score": "0-4" },
            { "min": "13", "scorer": "Constantin", "score": "0-5" },
            { "min": "15", "scorer": "Constantin", "score": "0-6" },
            { "min": "17", "scorer": "Inconnu", "score": "1-6" },
            { "min": "19", "scorer": "Inconnu", "score": "2-6" },
            { "min": "26", "scorer": "Romain", "score": "2-7" },
            { "min": "31", "scorer": "Inconnu", "score": "3-7" },
            { "min": "31", "scorer": "Inconnu", "score": "4-7" },
            { "min": "32", "scorer": "Inconnu", "score": "5-7" },
            { "min": "35", "scorer": "Romain", "score": "5-8" },
            { "min": "37", "scorer": "Inconnu", "score": "6-8" },
            { "min": "37", "scorer": "C", "score": "7-8" },
            { "min": "39", "scorer": "Romain", "score": "7-9" },
            { "min": "43", "scorer": "Inconnu", "score": "8-9" },
            { "min": "43", "scorer": "Constantin", "score": "8-10" },
            { "min": "45", "scorer": "C", "score": "9-10" },
            { "min": "46", "scorer": "Inconnu", "score": "9-11" },
            { "min": "47", "scorer": "Constantin", "score": "9-12" },
            { "min": "48", "scorer": "Inconnu", "score": "10-12" },
            { "min": "49", "scorer": "Inconnu", "score": "10-13" },
            { "min": "53", "scorer": "Abdel", "score": "10-14" },
            { "min": "54", "scorer": "Inconnu", "score": "11-14" },
            { "min": "56", "scorer": "Inconnu", "score": "11-15" },
            { "min": "58", "scorer": "Inconnu", "score": "12-15" }
        ]
    },
    {
        "date": "21/05/2025",
        "teamA": ["Florent", "Loïc", "Adrien", "Maxime", "Wasim"],
        "scoreA": 11,
        "teamB": ["Jesus", "Enos", "Constantin", "Driss", "François"],
        "scoreB": 9,
        "link": "https://drive.google.com/drive/folders/1x_HJbLIQpbFzyROsLgPRVHrMscJETYOy?usp=drive_link",
        "timeline": [
            { "min": "6", "scorer": "Loic", "score": "1-0" },
            { "min": "12", "scorer": "Max", "score": "2-0" },
            { "min": "17", "scorer": "Driss", "score": "2-1" },
            { "min": "18", "scorer": "Max", "score": "3-1" },
            { "min": "21", "scorer": "Enos", "score": "3-2" },
            { "min": "29", "scorer": "Jesus", "score": "3-3" },
            { "min": "31", "scorer": "Adri", "score": "4-3" },
            { "min": "31", "scorer": "Max", "score": "5-3" },
            { "min": "33", "scorer": "Jesus", "score": "5-4" },
            { "min": "35", "scorer": "Franc", "score": "5-5" },
            { "min": "37", "scorer": "Loic", "score": "6-5" },
            { "min": "39", "scorer": "Flo", "score": "7-5" },
            { "min": "41", "scorer": "Driss", "score": "7-6" },
            { "min": "42", "scorer": "Was", "score": "8-6" },
            { "min": "44", "scorer": "Adri", "score": "9-6" },
            { "min": "48", "scorer": "Adri", "score": "10-6" },
            { "min": "49", "scorer": "Franc", "score": "10-7" },
            { "min": "51", "scorer": "Inconnu", "score": "11-7" }
        ]
    },
    {
        "date": "23/05/2025",
        "teamA": ["Constantin", "Aniss", "Abderrhman", "Lamine", "François"],
        "scoreA": 12,
        "teamB": ["Jesus", "Youssef", "Driss", "Seyed", "Florent"],
        "scoreB": 10,
        "link": "https://drive.google.com/drive/folders/1ySjl5ghzq8NQz2rkYBtg33X5Xwvur1_i?usp=drive_link",
        "timeline": [
            { "min": "3", "scorer": "Inconnu", "score": "0-1" },
            { "min": "3", "scorer": "Inconnu", "score": "1-1" },
            { "min": "4", "scorer": "Inconnu", "score": "1-2" },
            { "min": "10", "scorer": "Inconnu", "score": "2-2" },
            { "min": "11", "scorer": "Inconnu", "score": "2-3" },
            { "min": "12", "scorer": "Inconnu", "score": "2-4" },
            { "min": "13", "scorer": "Inconnu", "score": "3-4" },
            { "min": "14", "scorer": "Inconnu", "score": "4-4" },
            { "min": "23", "scorer": "Inconnu", "score": "4-5" },
            { "min": "27", "scorer": "Inconnu", "score": "4-6" },
            { "min": "28", "scorer": "Inconnu", "score": "5-6" },
            { "min": "30", "scorer": "Inconnu", "score": "5-7" },
            { "min": "32", "scorer": "Inconnu", "score": "5-8" },
            { "min": "37", "scorer": "Inconnu", "score": "6-8" },
            { "min": "38", "scorer": "Inconnu", "score": "7-8" },
            { "min": "40", "scorer": "Inconnu", "score": "8-8" },
            { "min": "41", "scorer": "Inconnu", "score": "8-9" },
            { "min": "44", "scorer": "Inconnu", "score": "9-9" },
            { "min": "51", "scorer": "Inconnu", "score": "9-10" },
            { "min": "51", "scorer": "Inconnu", "score": "10-10" },
            { "min": "54", "scorer": "Inconnu", "score": "11-10" },
            { "min": "55", "scorer": "Inconnu", "score": "12-10" }
        ]
    },
    {
        "date": "27/05/2025",
        "teamA": ["Abdel Karim", "Andreja", "Lamine", "Florent", "Driss"],
        "scoreA": 12,
        "teamB": ["Weidong", "Romain", "Seyed", "Adrien", "Youssef"],
        "scoreB": 8,
        "link": "https://drive.google.com/drive/folders/1ySjl5ghzq8NQz2rkYBtg33X5Xwvur1_i?usp=drive_link",
        "timeline": [
            { "min": "6", "scorer": "Florent", "score": "1-0" },
            { "min": "8", "scorer": "Weidong", "score": "1-1" },
            { "min": "10", "scorer": "Lamine", "score": "2-1" },
            { "min": "16", "scorer": "Andreja", "score": "3-1" },
            { "min": "21", "scorer": "Andreja", "score": "4-1" },
            { "min": "22", "scorer": "Romain", "score": "4-2" },
            { "min": "24", "scorer": "Lamine", "score": "5-2" },
            { "min": "28", "scorer": "Romain", "score": "5-3" },
            { "min": "31", "scorer": "Weidong", "score": "5-4" },
            { "min": "32", "scorer": "Florent", "score": "6-4" },
            { "min": "35", "scorer": "Andreja", "score": "7-4" },
            { "min": "36", "scorer": "Lamine", "score": "8-4" },
            { "min": "38", "scorer": "Romain", "score": "8-5" },
            { "min": "44", "scorer": "Sayed", "score": "8-6" },
            { "min": "46", "scorer": "Andreja", "score": "9-6" },
            { "min": "46", "scorer": "Romain", "score": "9-7" },
            { "min": "49", "scorer": "Lamine", "score": "10-7" },
            { "min": "49", "scorer": "Karim", "score": "11-7" },
            { "min": "52", "scorer": "Andreja", "score": "12-7" },
            { "min": "54", "scorer": "Adrien", "score": "12-8" }
        ]
    },
    {
        "date": "06/06/2025",
        "teamA": ["Weidong", "Seyed", "Kevin", "Aniss", "Driss"],
        "scoreA": 8,
        "teamB": ["Constantin", "Romain", "Firas", "Wassim", "Lamine"],
        "scoreB": 10,
        "link": "https://drive.google.com/drive/folders/13irp-et3DFO1UzUHlrBDa2fTUOGx8J7V?usp=drive_link",
        "timeline": [
            { "min": "2", "scorer": "Inconnu", "score": "0-1" },
            { "min": "3", "scorer": "Inconnu", "score": "0-2" },
            { "min": "5", "scorer": "Inconnu", "score": "1-2" },
            { "min": "6", "scorer": "Inconnu", "score": "1-3" },
            { "min": "7", "scorer": "Inconnu", "score": "1-4" },
            { "min": "10", "scorer": "Inconnu", "score": "1-5" },
            { "min": "13", "scorer": "Inconnu", "score": "1-6" },
            { "min": "15", "scorer": "C", "score": "2-6" },
            { "min": "16", "scorer": "C", "score": "3-6" },
            { "min": "27", "scorer": "Inconnu", "score": "3-7" },
            { "min": "29", "scorer": "Inconnu", "score": "3-8" },
            { "min": "34", "scorer": "Inconnu", "score": "3-9" },
            { "min": "35", "scorer": "Inconnu", "score": "4-9" },
            { "min": "36", "scorer": "Inconnu", "score": "4-10" },
            { "min": "40", "scorer": "Inconnu", "score": "5-10" },
            { "min": "43", "scorer": "Inconnu", "score": "6-10" },
            { "min": "44", "scorer": "Inconnu", "score": "7-10" },
            { "min": "46", "scorer": "C", "score": "8-10" }
        ]
    },
    {
        "date": "15/08/2025",
        "teamA": ["Aaron", "Loic L", "Abdel Karim", "Constantin", "Mahdi"],
        "scoreA": 13,
        "teamB": ["Nizar", "Amine", "Driss", "Seyed", "Anasse"],
        "scoreB": 12,
        "link": "https://drive.google.com/drive/folders/12XmbtPICbUsafueq85jK3MnfRm3cSuYa?usp=drive_link",
        "timeline": [
            { "min": "10", "scorer": "Aaron", "score": "1-0" },
            { "min": "14", "scorer": "Nizar", "score": "1-1" },
            { "min": "15", "scorer": "Constan", "score": "2-1" },
            { "min": "16", "scorer": "Aaron", "score": "3-1" },
            { "min": "18", "scorer": "Nizar", "score": "3-2" },
            { "min": "22", "scorer": "Loic", "score": "4-2" },
            { "min": "24", "scorer": "Abdel", "score": "5-2" },
            { "min": "25", "scorer": "Mahdi", "score": "6-2" },
            { "min": "25", "scorer": "Nizar", "score": "6-3" },
            { "min": "28", "scorer": "Constan", "score": "7-3" },
            { "min": "28", "scorer": "Nizar", "score": "7-4" },
            { "min": "29", "scorer": "Mahdi", "score": "8-4" },
            { "min": "30", "scorer": "Amine", "score": "8-5" },
            { "min": "32", "scorer": "Nizar", "score": "8-6" },
            { "min": "33", "scorer": "Mahdi", "score": "9-6" },
            { "min": "38", "scorer": "Driss", "score": "9-7" },
            { "min": "40", "scorer": "Abdel", "score": "10-7" },
            { "min": "41", "scorer": "Nizar", "score": "10-8" },
            { "min": "41", "scorer": "Mahdi", "score": "11-8" },
            { "min": "42", "scorer": "Anass", "score": "11-9" },
            { "min": "45", "scorer": "Constan", "score": "12-9" },
            { "min": "48", "scorer": "Nizar", "score": "12-10" },
            { "min": "49", "scorer": "Sayed", "score": "12-11" },
            { "min": "50", "scorer": "Nizar", "score": "12-12" },
            { "min": "55", "scorer": "Loic L", "score": "13-12" }
        ]
    },
    {
        "date": "22/08/2025",
        "teamA": ["Nizar", "Driss", "Joseph", "Stephane", "Aaron"],
        "scoreA": 13,
        "teamB": ["Abdel Karim", "Constantin", "Amine", "Romain", "Seyed"],
        "scoreB": 15,
        "link": "https://drive.google.com/drive/folders/1RZYYptBGfCUlwNxCvLzEm97uj5K3GjPl?usp=drive_link",
        "timeline": [
            { "min": "11", "scorer": "Nizar", "score": "1-0" },
            { "min": "14", "scorer": "Seyed", "score": "1-1" },
            { "min": "15", "scorer": "Driss", "score": "2-1" },
            { "min": "16", "scorer": "Joseph", "score": "3-1" },
            { "min": "18", "scorer": "Joseph", "score": "4-1" },
            { "min": "18", "scorer": "Amine", "score": "4-2" },
            { "min": "19", "scorer": "Karim", "score": "4-3" },
            { "min": "22", "scorer": "Seyed", "score": "4-4" },
            { "min": "24", "scorer": "Nizar", "score": "5-4" },
            { "min": "26", "scorer": "Joseph", "score": "6-4" },
            { "min": "26", "scorer": "Seyed", "score": "6-5" },
            { "min": "28", "scorer": "Karim", "score": "6-6" },
            { "min": "30", "scorer": "Amine", "score": "6-7" },
            { "min": "30", "scorer": "Nizar", "score": "7-7" },
            { "min": "31", "scorer": "Nizar", "score": "8-7" },
            { "min": "32", "scorer": "Rom", "score": "8-8" },
            { "min": "34", "scorer": "Inconnu", "score": "8-9" },
            { "min": "35", "scorer": "Seyed", "score": "8-10" },
            { "min": "36", "scorer": "Joseph", "score": "9-10" },
            { "min": "39", "scorer": "Driss", "score": "10-10" },
            { "min": "41", "scorer": "Karim", "score": "10-11" },
            { "min": "43", "scorer": "Rom", "score": "10-12" },
            { "min": "45", "scorer": "Driss", "score": "11-12" },
            { "min": "49", "scorer": "Amine", "score": "11-13" },
            { "min": "52", "scorer": "Joseph", "score": "12-13" },
            { "min": "52", "scorer": "Rom", "score": "12-14" },
            { "min": "56", "scorer": "Karim", "score": "12-15" },
            { "min": "56", "scorer": "Driss", "score": "13-15" }
        ]
    },
    {
        "date": "29/08/2025",
        "teamA": ["Romain", "Abdel Karim", "Lamine", "Joseph", "Amine"],
        "scoreA": 12,
        "teamB": ["Seyed", "Mahdi", "Youssef", "Sofiane", "Abdelkader"],
        "scoreB": 12,
        "link": "https://drive.google.com/drive/folders/1rwS458lhBss-2t-SY0-VWxC2YDApoGlC?usp=drive_link",
        "timeline": []
    },
    {
        "date": "05/09/2025",
        "teamA": ["Constantin", "Seyed", "Youssef", "Mahdi", "Sofiane"],
        "scoreA": 13,
        "teamB": ["Kevin", "Aniss", "Amine", "Joseph", "Wasim"],
        "scoreB": 13,
        "link": "https://drive.google.com/drive/folders/1-Hm-RBmkHTCXOJ4QFOx1H_h6ivoedbyR?usp=drive_link",
        "timeline": [
            { "min": "6", "scorer": "Joseph", "score": "0-1" },
            { "min": "7", "scorer": "Mahdi", "score": "1-1" },
            { "min": "10", "scorer": "Youssef", "score": "2-1" },
            { "min": "13", "scorer": "Youssef", "score": "3-1" },
            { "min": "16", "scorer": "Aniss", "score": "3-2" },
            { "min": "18", "scorer": "Kevin", "score": "3-3" },
            { "min": "19", "scorer": "Aniss", "score": "3-4" },
            { "min": "20", "scorer": "Wassim", "score": "3-5" },
            { "min": "25", "scorer": "Joseph", "score": "3-6" },
            { "min": "26", "scorer": "Mahdi", "score": "4-6" },
            { "min": "32", "scorer": "Joseph", "score": "4-7" },
            { "min": "33", "scorer": "Mahdi", "score": "5-7" },
            { "min": "36", "scorer": "Joseph", "score": "5-8" },
            { "min": "37", "scorer": "Amine", "score": "5-9" },
            { "min": "38", "scorer": "Sofiane", "score": "6-9" },
            { "min": "39", "scorer": "Sofiane", "score": "7-9" },
            { "min": "42", "scorer": "Kevin", "score": "7-10" },
            { "min": "43", "scorer": "Sofiane", "score": "8-10" },
            { "min": "44", "scorer": "Sofiane", "score": "9-10" },
            { "min": "47", "scorer": "Mahdi", "score": "10-10" },
            { "min": "48", "scorer": "Seyed", "score": "11-10" },
            { "min": "52", "scorer": "Joseph", "score": "11-11" },
            { "min": "52", "scorer": "Mahdi", "score": "12-11" },
            { "min": "56", "scorer": "Kevin", "score": "12-12" },
            { "min": "57", "scorer": "Kevin", "score": "12-13" },
            { "min": "60", "scorer": "Seyed", "score": "13-13" }
        ]
    },
    {
        "date": "25/09/2025",
        "teamA": ["Florent", "Lamine", "Driss", "Aniss", "Abdel Karim"],
        "scoreA": 11,
        "teamB": ["Abderrhman", "Nizar", "Joseph", "Mahdi", "Mario"],
        "scoreB": 10,
        "link": "https://drive.google.com/drive/folders/16vu79gj0Kjv8fSqsk49B4I16V2waorAL?usp=drive_link",
        "timeline": [
            { "min": "1", "scorer": "Florent", "score": "1-0" },
            { "min": "4", "scorer": "Florent", "score": "2-0" },
            { "min": "7", "scorer": "Nizar", "score": "2-1" },
            { "min": "8", "scorer": "Nizar", "score": "2-2" },
            { "min": "11", "scorer": "Florent", "score": "3-2" },
            { "min": "15", "scorer": "Nizar", "score": "3-3" },
            { "min": "16", "scorer": "Florent", "score": "4-3" },
            { "min": "17", "scorer": "Nizar", "score": "4-4" },
            { "min": "20", "scorer": "Florent", "score": "5-4" },
            { "min": "29", "scorer": "Florent", "score": "6-4" },
            { "min": "31", "scorer": "Florent", "score": "7-4" },
            { "min": "32", "scorer": "Nizar", "score": "7-5" },
            { "min": "37", "scorer": "Nizar", "score": "7-6" },
            { "min": "40", "scorer": "Nizar", "score": "7-7" },
            { "min": "41", "scorer": "Florent", "score": "8-7" },
            { "min": "42", "scorer": "Nizar", "score": "8-8" },
            { "min": "46", "scorer": "Nizar", "score": "8-9" },
            { "min": "47", "scorer": "Florent", "score": "9-9" },
            { "min": "48", "scorer": "Florent", "score": "10-9" },
            { "min": "49", "scorer": "Nizar", "score": "10-10" },
            { "min": "58", "scorer": "Florent", "score": "11-10" }
        ]
    },
    {
        "date": "26/09/2025",
        "teamA": ["Constantin", "Seyed", "Wassim", "Loic L", "François"],
        "scoreA": 13,
        "teamB": ["Anasse", "Mahdi", "Romain", "Kevin", "Stephane"],
        "scoreB": 14,
        "link": "https://drive.google.com/drive/folders/14UK_QOTGM6Nml6nDTzIffvejBUSL4Y72?usp=sharing",
        "timeline": [
            { "min": "9", "scorer": "Kevin", "score": "0-1" },
            { "min": "9", "scorer": "Mahdi", "score": "0-2" },
            { "min": "14", "scorer": "Loic", "score": "1-2" },
            { "min": "14", "scorer": "Anasse", "score": "1-3" },
            { "min": "15", "scorer": "Constantin", "score": "2-3" },
            { "min": "26", "scorer": "Seyed", "score": "3-3" },
            { "min": "28", "scorer": "Romain", "score": "3-4" },
            { "min": "28", "scorer": "Wassim", "score": "4-4" },
            { "min": "29", "scorer": "Mahdi", "score": "4-5" },
            { "min": "32", "scorer": "Loic", "score": "5-5" },
            { "min": "34", "scorer": "Anasse", "score": "5-6" },
            { "min": "37", "scorer": "Wassim", "score": "6-6" },
            { "min": "41", "scorer": "Loic", "score": "7-6" },
            { "min": "44", "scorer": "Mahdi", "score": "7-7" },
            { "min": "45", "scorer": "Wassim", "score": "8-7" },
            { "min": "47", "scorer": "Kevin", "score": "8-8" },
            { "min": "47", "scorer": "Constantin", "score": "9-8" },
            { "min": "49", "scorer": "Loic", "score": "10-8" },
            { "min": "49", "scorer": "Kevin", "score": "10-9" },
            { "min": "50", "scorer": "Kevin", "score": "10-10" },
            { "min": "51", "scorer": "Romain", "score": "10-11" },
            { "min": "52", "scorer": "Wassim", "score": "11-11" },
            { "min": "52", "scorer": "Romain", "score": "11-12" },
            { "min": "53", "scorer": "Loic", "score": "12-12" },
            { "min": "55", "scorer": "Kevin", "score": "12-13" },
            { "min": "57", "scorer": "François", "score": "13-13" },
            { "min": "57", "scorer": "Mahdi", "score": "13-14" }
        ]
    },
    {
        "date": "09/10/2025",
        "teamA": ["Constantin", "Enos", "Jesus", "Loic L", "Mohamed"],
        "scoreA": 10,
        "teamB": ["Anasse", "Driss", "Florent", "Aniss", "Lamine"],
        "scoreB": 14,
        "link": "https://drive.google.com/drive/folders/1uTGn0YMUkgTue4u3Y5-3HPyNH8wStzIv?usp=drive_link",
        "timeline": [
            { "min": "7", "scorer": "Lamine", "score": "0-1" },
            { "min": "8", "scorer": "Loic", "score": "1-1" },
            { "min": "10", "scorer": "Lamine", "score": "1-2" },
            { "min": "13", "scorer": "Lamine", "score": "1-3" },
            { "min": "17", "scorer": "Loic", "score": "2-3" },
            { "min": "18", "scorer": "Enos", "score": "3-3" },
            { "min": "18", "scorer": "Anasse", "score": "3-4" },
            { "min": "19", "scorer": "Lamine", "score": "3-5" },
            { "min": "22", "scorer": "Jesus", "score": "4-5" },
            { "min": "24", "scorer": "Mohamed", "score": "5-5" },
            { "min": "25", "scorer": "Driss", "score": "5-6" },
            { "min": "26", "scorer": "Enos", "score": "6-6" },
            { "min": "29", "scorer": "Loic", "score": "7-6" },
            { "min": "34", "scorer": "Lamine", "score": "7-7" },
            { "min": "36", "scorer": "Anasse", "score": "7-8" },
            { "min": "40", "scorer": "aniss", "score": "7-9" },
            { "min": "41", "scorer": "Mohamed", "score": "8-9" },
            { "min": "41", "scorer": "Anasse", "score": "8-10" },
            { "min": "43", "scorer": "Florent", "score": "8-11" },
            { "min": "44", "scorer": "Loic", "score": "9-11" },
            { "min": "47", "scorer": "Constantin", "score": "10-11" },
            { "min": "50", "scorer": "Aniss", "score": "10-12" },
            { "min": "52", "scorer": "Florent", "score": "10-13" },
            { "min": "56", "scorer": "Driss", "score": "10-14" }
        ]
    },
    {
        "date": "17/10/2025",
        "teamA": ["Joseph", "Mahdi", "Romain", "Loic L", "Jesus"],
        "scoreA": 18,
        "teamB": ["Aniss", "Abdel Karim", "Nassim", "Seyed", "Stephane"],
        "scoreB": 5,
        "link": "https://drive.google.com/drive/folders/1vwOg3V_1XbjXlAzYXMj93sC_4PtYTVX4?usp=drive_link",
        "timeline": [
            { "min": "3", "scorer": "Joseph", "score": "1-0" },
            { "min": "4", "scorer": "Mahdi", "score": "2-0" },
            { "min": "8", "scorer": "Mahdi", "score": "3-0" },
            { "min": "8", "scorer": "Romain", "score": "4-0" },
            { "min": "9", "scorer": "Stephane", "score": "4-1" },
            { "min": "10", "scorer": "Romain", "score": "5-1" },
            { "min": "11", "scorer": "Nassim", "score": "5-2" },
            { "min": "13", "scorer": "Mahdi", "score": "6-2" },
            { "min": "15", "scorer": "Joseph", "score": "7-2" },
            { "min": "17", "scorer": "Jesus", "score": "8-2" },
            { "min": "19", "scorer": "Aniss", "score": "8-3" },
            { "min": "19", "scorer": "Romain", "score": "9-3" },
            { "min": "20", "scorer": "Nassim", "score": "9-4" },
            { "min": "25", "scorer": "Loic", "score": "10-4" },
            { "min": "28", "scorer": "Joseph", "score": "11-4" },
            { "min": "30", "scorer": "Mahdi", "score": "12-4" },
            { "min": "37", "scorer": "Romain", "score": "13-4" },
            { "min": "39", "scorer": "Loic", "score": "14-4" },
            { "min": "41", "scorer": "Seyed", "score": "14-5" },
            { "min": "42", "scorer": "Loic", "score": "15-5" },
            { "min": "44", "scorer": "Nassim", "score": "15-6" },
            { "min": "46", "scorer": "Seyed", "score": "15-7" },
            { "min": "46", "scorer": "Romain", "score": "16-7" },
            { "min": "51", "scorer": "Joseph", "score": "17-7" },
            { "min": "54", "scorer": "Loic", "score": "18-7" }
        ]
    },
    {
        "date": "24/10/2025",
        "teamA": ["Constantin", "Anasse", "François", "Aniss", "Lamine"],
        "scoreA": 7,
        "teamB": ["Adrien", "Briac", "Loic L", "Driss", "Florent"],
        "scoreB": 7,
        "link": "https://drive.google.com/drive/folders/1gYfL7utSFXSF9LKtbTiP8moZPUDq2vJj?usp=drive_link",
        "timeline": [
            { "min": "2", "scorer": "Constantin", "score": "1-0" },
            { "min": "6", "scorer": "François", "score": "2-0" },
            { "min": "7", "scorer": "Florent", "score": "2-1" },
            { "min": "17", "scorer": "Briac", "score": "2-2" },
            { "min": "21", "scorer": "François", "score": "3-2" },
            { "min": "23", "scorer": "François", "score": "4-2" },
            { "min": "25", "scorer": "Adrien", "score": "4-3" },
            { "min": "27", "scorer": "Loic", "score": "4-4" },
            { "min": "28", "scorer": "Adrien", "score": "4-5" },
            { "min": "30", "scorer": "Loic", "score": "4-6" },
            { "min": "33", "scorer": "Lamine", "score": "5-6" },
            { "min": "42", "scorer": "Lamine", "score": "6-6" },
            { "min": "43", "scorer": "Briac", "score": "6-7" },
            { "min": "47", "scorer": "Lamine", "score": "7-7" }
        ]
    },
    {
        "date": "04/11/2025",
        "teamA": ["Enos", "Anasse", "Driss", "Loic L", "Nizar"],
        "scoreA": 10,
        "teamB": ["Seyed", "Abdel Karim", "Lamine", "Adrien", "Florent"],
        "scoreB": 7,
        "link": "",
        "timeline": []
    },
    {
        "date": "07/11/2025",
        "teamA": ["Romain", "Mahdi", "Aniss", "Joseph", "Briac"],
        "scoreA": 13,
        "teamB": ["Anasse", "Driss", "Youssef", "François", "Loic L"],
        "scoreB": 14,
        "link": "",
        "timeline": [
            { "min": "1", "scorer": "Anasse", "score": "0-1" },
            { "min": "3", "scorer": "Loic L", "score": "0-2" },
            { "min": "3", "scorer": "Briac", "score": "1-2" },
            { "min": "4", "scorer": "Braic", "score": "2-2" },
            { "min": "6", "scorer": "Romain", "score": "3-2" },
            { "min": "6", "scorer": "Loic L", "score": "3-3" },
            { "min": "10", "scorer": "Mahdi", "score": "4-3" },
            { "min": "16", "scorer": "Mahdi", "score": "5-3" },
            { "min": "17", "scorer": "Aniss", "score": "6-3" },
            { "min": "20", "scorer": "Loic L", "score": "6-4" },
            { "min": "21", "scorer": "Briac", "score": "7-4" },
            { "min": "22", "scorer": "Mahdi", "score": "8-4" },
            { "min": "25", "scorer": "Mahdi", "score": "9-4" },
            { "min": "27", "scorer": "Youssef", "score": "9-5" },
            { "min": "28", "scorer": "Romain", "score": "10-5" },
            { "min": "29", "scorer": "Youssef", "score": "9-5" },
            { "min": "29", "scorer": "Loic L", "score": "10-7" },
            { "min": "30", "scorer": "Loic L", "score": "10-8" },
            { "min": "31", "scorer": "Briac", "score": "11-8" },
            { "min": "34", "scorer": "Youssef", "score": "11-9" },
            { "min": "35", "scorer": "Joseph", "score": "12-9" },
            { "min": "38", "scorer": "Mahdi", "score": "13-9" },
            { "min": "43", "scorer": "Loic", "score": "13-10" },
            { "min": "48", "scorer": "François", "score": "13-11" },
            { "min": "48", "scorer": "Youssef", "score": "13-12" },
            { "min": "50", "scorer": "Driss", "score": "13-13" },
            { "min": "51", "scorer": "Youssef", "score": "13-14" }
        ]
    },
    {
        "date": "25/11/2025",
        "teamA": ["Constantin", "Enos", "Romain", "Anas", "Lamine"],
        "scoreA": 8,
        "teamB": ["Jesus", "Abdel Karim", "Anasse", "Nassim", "Driss"],
        "scoreB": 8,
        "link": "",
        "timeline": [
            { "min": "7", "scorer": "Romain", "score": "1-0" },
            { "min": "8", "scorer": "Constantin", "score": "2-0" },
            { "min": "13", "scorer": "Anas", "score": "3-0" },
            { "min": "14", "scorer": "Jesus", "score": "3-1" },
            { "min": "15", "scorer": "Anasse", "score": "3-2" },
            { "min": "16", "scorer": "Lamine", "score": "4-2" },
            { "min": "22", "scorer": "Enos", "score": "5-2" },
            { "min": "26", "scorer": "Jesus", "score": "5-3" },
            { "min": "28", "scorer": "Anas", "score": "6-3" },
            { "min": "30", "scorer": "Karim", "score": "6-4" },
            { "min": "35", "scorer": "Jesus", "score": "6-5" },
            { "min": "36", "scorer": "Nassim", "score": "6-6" },
            { "min": "44", "scorer": "Romain", "score": "7-6" },
            { "min": "46", "scorer": "Nassim", "score": "7-7" },
            { "min": "52", "scorer": "Inconnu", "score": "7-8" },
            { "min": "53", "scorer": "Romain", "score": "8-8" }
        ]
    },
    {
        "date": "17/12/2025",
        "teamA": ["Constantin", "Anasse", "Driss", "Youssef", "Aniss"],
        "scoreA": 9,
        "teamB": ["Esteban", "Joseph", "Briac", "Weidong", "Florent"],
        "scoreB": 17,
        "link": "",
        "timeline": [
            { "min": "8", "scorer": "Esteban", "score": "0-1" },
            { "min": "11", "scorer": "Youssef", "score": "1-1" },
            { "min": "11", "scorer": "Esteban", "score": "1-2" },
            { "min": "13", "scorer": "Anasse", "score": "2-2" },
            { "min": "14", "scorer": "Weidong", "score": "2-3" },
            { "min": "15", "scorer": "Esteban", "score": "2-4" },
            { "min": "17", "scorer": "Weidong", "score": "2-5" },
            { "min": "20", "scorer": "Aniss", "score": "3-5" },
            { "min": "21", "scorer": "Weidong", "score": "3-6" },
            { "min": "22", "scorer": "Aniss", "score": "4-6" },
            { "min": "23", "scorer": "Youssef", "score": "5-6" },
            { "min": "24", "scorer": "Youssef", "score": "6-6" },
            { "min": "25", "scorer": "Youssef", "score": "7-6" },
            { "min": "26", "scorer": "Briac", "score": "7-7" },
            { "min": "30", "scorer": "Esteban", "score": "7-8" },
            { "min": "31", "scorer": "Briac", "score": "7-9" },
            { "min": "32", "scorer": "Florent", "score": "7-10" },
            { "min": "33", "scorer": "Florent", "score": "7-11" },
            { "min": "34", "scorer": "Constantin", "score": "7-12" },
            { "min": "35", "scorer": "Briac", "score": "7-13" },
            { "min": "36", "scorer": "Joseph", "score": "7-14" },
            { "min": "41", "scorer": "Inconnu", "score": "8-14" },
            { "min": "43", "scorer": "Weidong", "score": "8-15" },
            { "min": "50", "scorer": "Esteban", "score": "8-16" },
            { "min": "53", "scorer": "Briac", "score": "8-17" },
            { "min": "54", "scorer": "Youssef", "score": "9-17" },
            { "min": "56", "scorer": "Weidong", "score": "9-18" }
        ]
    },
    {
        "date": "22/12/2025",
        "teamA": ["Enos", "Constantin", "Mohamed", "Lamine", "Jesus"],
        "scoreA": 7,
        "teamB": ["Abderrhman", "Loic L", "Driss", "Karim", "Anasse"],
        "scoreB": 7,
        "link": "",
        "timeline": [
            { "min": "3", "scorer": "Loic", "score": "0-1" },
            { "min": "5", "scorer": "Enos", "score": "1-1" },
            { "min": "7", "scorer": "Constantin", "score": "2-1" },
            { "min": "7", "scorer": "Enos", "score": "3-1" },
            { "min": "13", "scorer": "Mohamed", "score": "4-1" },
            { "min": "16", "scorer": "Loic", "score": "4-2" },
            { "min": "22", "scorer": "Constantin", "score": "5-2" },
            { "min": "23", "scorer": "Loic", "score": "5-3" },
            { "min": "23", "scorer": "Lamine", "score": "6-3" },
            { "min": "26", "scorer": "Abde", "score": "6-4" },
            { "min": "29", "scorer": "Abde", "score": "6-5" },
            { "min": "33", "scorer": "Enos", "score": "7-5" },
            { "min": "36", "scorer": "Abde", "score": "7-6" },
            { "min": "40", "scorer": "Loic", "score": "7-7" }
        ]
    },
    {
        "date": "21/01/2026",
        "teamA": ["Fabrice", "Maxime", "Kevin", "Constantin", "Lamine"],
        "scoreA": 15,
        "teamB": ["Driss", "Youssef", "Aniss", "Esteban", "Anasse"],
        "scoreB": 12,
        "link": "",
        "timeline": [
            { "min": "1", "scorer": "Inconnu", "score": "0-1" },
            { "min": "2", "scorer": "Driss", "score": "0-2" },
            { "min": "3", "scorer": "Driss", "score": "0-3" },
            { "min": "4", "scorer": "Driss", "score": "0-4" },
            { "min": "7", "scorer": "Driss", "score": "0-5" },
            { "min": "8", "scorer": "Max", "score": "1-5" },
            { "min": "9", "scorer": "Driss", "score": "1-6" },
            { "min": "9", "scorer": "Driss", "score": "1-7" },
            { "min": "10", "scorer": "Driss", "score": "1-8" },
            { "min": "11", "scorer": "Esteban", "score": "2-8" },
            { "min": "19", "scorer": "Max", "score": "3-8" },
            { "min": "21", "scorer": "Inconnu", "score": "3-9" },
            { "min": "23", "scorer": "Max", "score": "4-9" },
            { "min": "23", "scorer": "Driss", "score": "4-10" },
            { "min": "24", "scorer": "Anass", "score": "5-10" },
            { "min": "27", "scorer": "Esteban", "score": "6-10" },
            { "min": "28", "scorer": "Inconnu", "score": "7-10" },
            { "min": "31", "scorer": "Driss", "score": "7-11" },
            { "min": "31", "scorer": "Driss", "score": "7-12" },
            { "min": "32", "scorer": "Driss", "score": "7-13" },
            { "min": "36", "scorer": "Esteban", "score": "8-13" },
            { "min": "39", "scorer": "Max", "score": "9-13" },
            { "min": "40", "scorer": "Driss", "score": "9-14" },
            { "min": "44", "scorer": "Anass", "score": "10-14" },
            { "min": "45", "scorer": "Anass", "score": "11-14" },
            { "min": "46", "scorer": "Max", "score": "12-14" },
            { "min": "49", "scorer": "Driss", "score": "12-15" }
        ]
    },
    {
        "date": "28/01/2026",
        "teamA": ["Romain", "Lamine", "Adrien", "Florent", "Mohamed"],
        "scoreA": 4,
        "teamB": ["Constantin", "Anasse", "Maxime", "Aniss", "Loic L"],
        "scoreB": 9,
        "link": "",
        "timeline": [
            { "min": "8", "scorer": "Maxime", "score": "0-1" },
            { "min": "13", "scorer": "Mohamed A", "score": "1-1" },
            { "min": "15", "scorer": "Loic", "score": "1-2" },
            { "min": "20", "scorer": "Anasse", "score": "1-3" },
            { "min": "21", "scorer": "Constantin", "score": "1-4" },
            { "min": "21", "scorer": "Adrien", "score": "2-4" },
            { "min": "22", "scorer": "Loic", "score": "2-5" },
            { "min": "29", "scorer": "Loic", "score": "2-6" },
            { "min": "37", "scorer": "Maxime", "score": "2-7" },
            { "min": "39", "scorer": "Constantin", "score": "2-8" },
            { "min": "42", "scorer": "Romain", "score": "3-8" },
            { "min": "44", "scorer": "Anasse", "score": "3-9" },
            { "min": "46", "scorer": "Lamine", "score": "4-9" }
        ]
    },
    {
        "date": "04/02/2026",
        "teamA": ["Esteban", "Nassim", "Thomas", "Constantin", "Fabrice"],
        "scoreA": 9,
        "teamB": ["Aniss", "Kerim", "Anasse", "Maxime", "Youssef"],
        "scoreB": 11,
        "link": "",
        "timeline": [
            { "min": "1", "scorer": "C", "score": "1-0" },
            { "min": "5", "scorer": "Inconnu", "score": "1-1" },
            { "min": "8", "scorer": "C", "score": "2-1" },
            { "min": "12", "scorer": "C", "score": "3-1" },
            { "min": "13", "scorer": "Inconnu", "score": "3-2" },
            { "min": "15", "scorer": "C", "score": "4-2" },
            { "min": "15", "scorer": "Inconnu", "score": "4-3" },
            { "min": "17", "scorer": "Inconnu", "score": "4-4" },
            { "min": "18", "scorer": "Inconnu", "score": "4-5" },
            { "min": "22", "scorer": "Inconnu", "score": "4-6" },
            { "min": "25", "scorer": "C", "score": "5-6" },
            { "min": "25", "scorer": "C", "score": "6-6" },
            { "min": "34", "scorer": "Inconnu", "score": "6-7" },
            { "min": "36", "scorer": "C", "score": "7-7" },
            { "min": "36", "scorer": "C", "score": "8-7" },
            { "min": "41", "scorer": "C", "score": "9-7" },
            { "min": "44", "scorer": "Inconnu", "score": "9-8" },
            { "min": "44", "scorer": "C", "score": "10-8" },
            { "min": "46", "scorer": "Inconnu", "score": "10-9" },
            { "min": "47", "scorer": "C", "score": "11-9" }
        ]
    },
    {
        "date": "11/02/2026",
        "teamA": ["Anasse", "Lamine", "Driss", "Selim", "Fabrice"],
        "scoreA": 5,
        "teamB": ["Constantin", "Romain", "Joyce", "Loic L", "Jesus"],
        "scoreB": 7,
        "link": "",
        "timeline": [
            { "min": "1", "scorer": "Inconnu", "score": "1-0" },
            { "min": "3", "scorer": "Constantin", "score": "1-1" },
            { "min": "8", "scorer": "Joyce", "score": "1-2" },
            { "min": "12", "scorer": "Loic", "score": "1-3" },
            { "min": "13", "scorer": "Lamine", "score": "2-3" },
            { "min": "17", "scorer": "Romain", "score": "2-4" },
            { "min": "17", "scorer": "Romain", "score": "2-5" },
            { "min": "18", "scorer": "Romain", "score": "2-6" },
            { "min": "19", "scorer": "Romain", "score": "2-7" },
            { "min": "20", "scorer": "Lamine", "score": "3-7" },
            { "min": "27", "scorer": "Selim", "score": "4-7" },
            { "min": "29", "scorer": "Inconnu", "score": "5-7" }
        ]
    },
    {
        "date": "16/02/2026",
        "teamA": ["Youssef", "Seyed", "Constantin", "Driss", "Poteau"],
        "scoreA": 7,
        "teamB": ["Fabrice", "Romain", "Anasse", "Joyce", "Philippe"],
        "scoreB": 10,
        "link": "",
        "timeline": [
            { "min": "1", "scorer": "Youssef", "score": "1-0" },
            { "min": "10", "scorer": "Fabrice", "score": "1-1" },
            { "min": "18", "scorer": "Romain", "score": "1-2" },
            { "min": "21", "scorer": "Seyed", "score": "2-2" },
            { "min": "23", "scorer": "Fabrice", "score": "2-3" },
            { "min": "26", "scorer": "Romain", "score": "2-4" },
            { "min": "27", "scorer": "Youssef", "score": "3-4" },
            { "min": "30", "scorer": "Romain", "score": "3-5" },
            { "min": "35", "scorer": "Youssef", "score": "4-5" },
            { "min": "36", "scorer": "Seyed", "score": "5-5" },
            { "min": "37", "scorer": "Romain", "score": "5-6" },
            { "min": "38", "scorer": "Anasse", "score": "5-7" },
            { "min": "49", "scorer": "Youssef", "score": "6-7" },
            { "min": "50", "scorer": "Fabrice", "score": "6-8" },
            { "min": "51", "scorer": "Fabrice", "score": "7-9" },
            { "min": "56", "scorer": "Joyce", "score": "7-10" }
        ]
    },
    {
        "date": "17/02/2026",
        "teamA": ["Maxime", "Lamine", "Constantin", "Briac", "Anasse"],
        "scoreA": 9,
        "teamB": ["Mahdi", "Driss", "Loic R", "Fabrice", "Philippe"],
        "scoreB": 12,
        "link": "",
        "timeline": [
            { "min": "8", "scorer": "Mahdi", "score": "0-1" },
            { "min": "11", "scorer": "Driss", "score": "0-2" },
            { "min": "12", "scorer": "Maxime", "score": "1-2" },
            { "min": "12", "scorer": "Loic", "score": "1-3" },
            { "min": "13", "scorer": "Mahdi", "score": "1-4" },
            { "min": "16", "scorer": "Lamine", "score": "2-4" },
            { "min": "21", "scorer": "Briac", "score": "3-4" },
            { "min": "24", "scorer": "Maxime", "score": "4-4" },
            { "min": "25", "scorer": "Constantin", "score": "5-4" },
            { "min": "30", "scorer": "Driss", "score": "5-5" },
            { "min": "38", "scorer": "Fabrice", "score": "5-6" },
            { "min": "42", "scorer": "Maxime", "score": "6-6" },
            { "min": "43", "scorer": "Loic", "score": "6-7" },
            { "min": "43", "scorer": "Loic", "score": "6-8" },
            { "min": "44", "scorer": "Loic", "score": "6-9" },
            { "min": "45", "scorer": "Fabrice", "score": "6-10" },
            { "min": "46", "scorer": "Driss", "score": "6-11" },
            { "min": "46", "scorer": "Anasse", "score": "7-11" },
            { "min": "49", "scorer": "Maxime", "score": "8-11" },
            { "min": "49", "scorer": "Briac", "score": "9-11" },
            { "min": "51", "scorer": "Mahdi", "score": "9-12" }
        ]
    },
    {
        "date": "18/02/2026",
        "teamA": ["Constantin", "Kerim", "Joyce", "Selim", "Thomas"],
        "scoreA": 12,
        "teamB": ["Driss", "Loic L", "Christian", "Romain", "Anasse"],
        "scoreB": 8,
        "link": "",
        "timeline": [
            { "min": "9", "scorer": "Constantin", "score": "1-0" },
            { "min": "11", "scorer": "Kerim", "score": "2-0" },
            { "min": "11", "scorer": "Driss", "score": "2-1" },
            { "min": "13", "scorer": "Loic", "score": "2-2" },
            { "min": "14", "scorer": "Kerim", "score": "3-2" },
            { "min": "16", "scorer": "Kerim", "score": "4-2" },
            { "min": "21", "scorer": "Romain", "score": "4-3" },
            { "min": "24", "scorer": "Joyce", "score": "5-3" },
            { "min": "25", "scorer": "Loic", "score": "5-4" },
            { "min": "27", "scorer": "Romain", "score": "5-5" },
            { "min": "28", "scorer": "Romain", "score": "5-6" },
            { "min": "29", "scorer": "Kerim", "score": "6-6" },
            { "min": "34", "scorer": "Joyce", "score": "7-6" },
            { "min": "37", "scorer": "Christian", "score": "7-7" },
            { "min": "38", "scorer": "Selim", "score": "8-7" },
            { "min": "40", "scorer": "Joyce", "score": "9-7" },
            { "min": "40", "scorer": "Christian", "score": "9-8" },
            { "min": "41", "scorer": "Joyce", "score": "10-8" },
            { "min": "45", "scorer": "Constantin", "score": "11-8" },
            { "min": "49", "scorer": "Kerim", "score": "12-8" }
        ]
    },
    {
        "date": "25/02/2026",
        "teamA": ["Briac", "Loic R", "Joyce", "Youssef", "Driss"],
        "scoreA": 10,
        "teamB": ["Fabrice", "Slimane", "Romain", "Constantin", "Kerim"],
        "scoreB": 14,
        "link": "",
        "timeline": [
            { "min": "7", "scorer": "Briac", "score": "1-0" },
            { "min": "9", "scorer": "Briac", "score": "2-0" },
            { "min": "10", "scorer": "Fabrice", "score": "2-1" },
            { "min": "12", "scorer": "Loic", "score": "3-1" },
            { "min": "22", "scorer": "Slimane", "score": "3-2" },
            { "min": "23", "scorer": "Slimane", "score": "3-3" },
            { "min": "25", "scorer": "Kerim", "score": "3-4" },
            { "min": "30", "scorer": "Romain Prime", "score": "3-5" },
            { "min": "31", "scorer": "Joyce", "score": "4-5" },
            { "min": "35", "scorer": "Fabrice", "score": "4-6" },
            { "min": "40", "scorer": "Romain Prime", "score": "4-7" },
            { "min": "42", "scorer": "Fabrice", "score": "4-8" },
            { "min": "43", "scorer": "Kerim", "score": "4-9" },
            { "min": "45", "scorer": "Joyce", "score": "5-9" },
            { "min": "47", "scorer": "Briac", "score": "6-9" },
            { "min": "48", "scorer": "Fabrice", "score": "6-10" },
            { "min": "49", "scorer": "Romain Prime", "score": "6-11" },
            { "min": "53", "scorer": "Fabrice", "score": "6-12" },
            { "min": "55", "scorer": "Slimane", "score": "6-13" },
            { "min": "56", "scorer": "Joyce", "score": "7-13" },
            { "min": "58", "scorer": "Youssef", "score": "8-13" },
            { "min": "58", "scorer": "Youssef", "score": "9-13" },
            { "min": "60", "scorer": "Fabrice", "score": "9-14" },
            { "min": "60", "scorer": "Loic", "score": "10-14" }
        ]
    },
    {
        "date": "04/03/2026",
        "teamA": ["Romain", "Youssef", "Maxime", "Jesus", "Anasse"],
        "scoreA": 9,
        "teamB": ["Aniss", "Kerim", "Driss", "Constantin", "Fabrice"],
        "scoreB": 7,
        "link": "",
        "timeline": [
            { "min": "5", "scorer": "Aniss", "score": "0-1" },
            { "min": "7", "scorer": "Fabrice", "score": "0-2" },
            { "min": "10", "scorer": "Drissou", "score": "0-3" },
            { "min": "10", "scorer": "Romain", "score": "1-3" },
            { "min": "12", "scorer": "Youssef", "score": "2-3" },
            { "min": "17", "scorer": "Youssef", "score": "3-3" },
            { "min": "23", "scorer": "Fabrice", "score": "3-4" },
            { "min": "25", "scorer": "Romain", "score": "4-4" },
            { "min": "28", "scorer": "Youssef", "score": "5-4" },
            { "min": "31", "scorer": "Max", "score": "6-4" },
            { "min": "33", "scorer": "Kerim", "score": "6-5" },
            { "min": "37", "scorer": "Drissou", "score": "6-6" },
            { "min": "44", "scorer": "Youssef", "score": "7-6" },
            { "min": "45", "scorer": "Constant1", "score": "7-7" },
            { "min": "51", "scorer": "Youssef", "score": "8-7" },
            { "min": "55", "scorer": "Youssef", "score": "9-7" }
        ]
    },
    {
        "date": "09/03/2026",
        "teamA": ["Constantin", "Joyce", "Kevin", "Romain", "Driss"],
        "scoreA": 16,
        "teamB": ["Maxime", "Anasse", "Youssef", "Seyed", "Philippe"],
        "scoreB": 15,
        "link": "",
        "timeline": [
            { "min": "4", "scorer": "Constantin", "score": "1-0" },
            { "min": "6", "scorer": "Joyce", "score": "2-0" },
            { "min": "8", "scorer": "Youssef", "score": "2-1" },
            { "min": "12", "scorer": "Seyed", "score": "2-2" },
            { "min": "15", "scorer": "Youssef", "score": "2-3" },
            { "min": "17", "scorer": "Maxime", "score": "2-4" },
            { "min": "19", "scorer": "Youssef", "score": "2-5" },
            { "min": "19", "scorer": "Seyed", "score": "2-6" },
            { "min": "21", "scorer": "Seyed", "score": "2-7" },
            { "min": "22", "scorer": "Seyed", "score": "2-8" },
            { "min": "23", "scorer": "Kevin", "score": "3-8" },
            { "min": "26", "scorer": "Maxime", "score": "3-9" },
            { "min": "27", "scorer": "Youssef", "score": "3-10" },
            { "min": "28", "scorer": "Joyce", "score": "4-10" },
            { "min": "30", "scorer": "Seyed", "score": "4-11" },
            { "min": "30", "scorer": "Constantin", "score": "5-11" },
            { "min": "35", "scorer": "Romain", "score": "6-11" },
            { "min": "38", "scorer": "Romain", "score": "7-11" },
            { "min": "39", "scorer": "Kevin", "score": "8-11" },
            { "min": "40", "scorer": "Maxime", "score": "8-12" },
            { "min": "41", "scorer": "Kevin", "score": "9-12" },
            { "min": "42", "scorer": "Kevin", "score": "10-12" },
            { "min": "47", "scorer": "Kevin", "score": "11-12" },
            { "min": "50", "scorer": "Youssef", "score": "11-13" },
            { "min": "50", "scorer": "Romain", "score": "12-13" },
            { "min": "52", "scorer": "Kevin", "score": "13-13" },
            { "min": "53", "scorer": "Seyed", "score": "13-14" },
            { "min": "54", "scorer": "Driss", "score": "14-14" },
            { "min": "56", "scorer": "Driss", "score": "15-14" },
            { "min": "58", "scorer": "Seyed", "score": "15-15" },
            { "min": "60", "scorer": "Kevin", "score": "16-15" }
        ]
    },
    {
        "date": "11/03/2026",
        "teamA": ["Constantin", "Jesus", "Romain", "Maxime", "Loic L"],
        "scoreA": 8,
        "teamB": ["Driss", "Anasse", "Youssef", "Mohamed", "Aniss"],
        "scoreB": 7,
        "link": "",
        "timeline": [
            { "min": "4", "scorer": "Youssef", "score": "1-0" },
            { "min": "14", "scorer": "Jesus 0", "score": "1-1" },
            { "min": "18", "scorer": "Maxime", "score": "1-2" },
            { "min": "20", "scorer": "Anis", "score": "2-2" },
            { "min": "21", "scorer": "Loic 0", "score": "2-3" },
            { "min": "25", "scorer": "Mohamed 6", "score": "3-3" },
            { "min": "29", "scorer": "Maxime", "score": "3-4" },
            { "min": "30", "scorer": "Romain", "score": "3-5" },
            { "min": "35", "scorer": "Anis", "score": "4-5" },
            { "min": "36", "scorer": "Youssef", "score": "5-5" },
            { "min": "37", "scorer": "Loic 0", "score": "5-6" },
            { "min": "40", "scorer": "Maxime", "score": "5-7" },
            { "min": "41", "scorer": "Anis", "score": "6-7" },
            { "min": "46", "scorer": "Driss", "score": "7-7" },
            { "min": "49", "scorer": "Maxime", "score": "7-8" }
        ]
    },
    {
        "date": "18/03/2026",
        "teamA": ["Constantin", "Abdel Karim", "Driss", "Joyce", "Mohamed"],
        "scoreA": 10,
        "teamB": ["Fabrice", "Anasse", "Enos", "Briac", "Maxime"],
        "scoreB": 6,
        "link": "",
        "timeline": [
            { "min": "9", "scorer": "Karim", "score": "1-0" },
            { "min": "18", "scorer": "Joyce", "score": "2-0" },
            { "min": "19", "scorer": "Mohamed", "score": "3-0" },
            { "min": "21", "scorer": "Constantin", "score": "4-0" },
            { "min": "21", "scorer": "Enos", "score": "4-1" },
            { "min": "30", "scorer": "Constantin", "score": "5-1" },
            { "min": "31", "scorer": "Anasse", "score": "5-2" },
            { "min": "32", "scorer": "Fabrice", "score": "5-3" },
            { "min": "34", "scorer": "Fabrice", "score": "5-4" },
            { "min": "36", "scorer": "Joyce", "score": "6-4" },
            { "min": "37", "scorer": "Fabrice", "score": "6-5" },
            { "min": "38", "scorer": "Constantin", "score": "7-5" },
            { "min": "42", "scorer": "Fabrice", "score": "7-6" },
            { "min": "43", "scorer": "Joyce", "score": "8-6" },
            { "min": "60", "scorer": "Karim", "score": "9-6" },
            { "min": "60", "scorer": "Constantin", "score": "10-6" }
        ]
    }
];